[package]
name = "x"
version = "0.0.1"
description = """
Command runner
"""
authors = ["Victor Menge <victotr.ferreira.menge@toolsforhumanity.com>"]
publish = false
edition = "2024"

[dependencies]
clap = { version = "4.5.59", features = ["derive"] }
color-eyre = "0.6.5"
